### ISSUE TITLE
State of GRASS presentation at FOSS4G 2023

### ISSUE THREAD

**Issue by veroandreo** [ctu-geoforall-lab/grass-gis-talk-foss4g-2023#1]
Hello @landam ! 

Shall we start preparing the presentation? Date is quickly approaching :wink: 

Aside from general stuff, I think that the [highlights](https://github.com/OSGeo/grass/releases/tag/8.3.0RC1) in the RC1 description + [results](https://grasswiki.osgeo.org/wiki/Talk:GRASS_Community_Meeting_Prague_2023) from the community meeting in Prague are good starting points, what do others think?

**Comment by neteler** [comment]
One can see the current state rendered like this:

http://htmlpreview.github.io/?https://github.com/ctu-geoforall-lab/grass-gis-talk-foss4g-2023/blob/main/foss4g2023.html#/

Note that there an MANY outcommented slides in `foss4g2023.html` which could be of interest for the upcoming conference.

**Comment by wenzeslaus** [comment]
You can simply use for https://ctu-geoforall-lab.github.io/grass-gis-talk-foss4g-2023/foss4g2023.html#/ The slides are published just the main repo page misses the link.

I don't see anything in the slides in comments. Do you have something specific in mind?
